General:
  comment: PatchGCN
  seed: 2021
  epochs: 20
  grad_acc: 16
  frozen_bn: false
  patience: 20
  server: train
Loss:
  loss_name: NLLSurvLoss
  alpha_surv: 0.4
Data:
  dataset_name: graph_data
  parent_dir: /home/data/tcga_prad/
  wsifeat_dir: histo_model_preproc/1024_40/UNI/pt_graphs
  clin_file: tabular_data/clindata/tcga_prad_clin_imputed.csv
  label_dir: tabular_data/cross_val_tables/seed99999/batchstrat
  omics_file: tabular_data/genomicdata/rnaseq_in_pways_tpm.csv
  log_path: logs/patchGCN_batchstrat_dseed99999_patchsize1024_encoderUNI_noclin_alpha0.4_lr0.0005
  max_slides: 1
  train_dataloader:
    batch_size: 1
    num_workers: 1
  test_dataloader:
    batch_size: 1
    num_workers: 1
ModelInfo:
  name: PatchGCN
  params:
    n_classes: 4
    concat_hidden_sizes:
    - 16
    - 8
    wsi_hidden_sizes: null
    pretrain_clin: false
    clin_vars: []
  n_classes: 4
Optimizer:
  opt: adam
  lr: 0.0005
  weight_decay: 1.0e-05
