General:
  comment: CLAM
  seed: 2021
  grad_acc: 16
  epochs: 20
  frozen_bn: false
  patience: 20
  server: train
Loss:
  loss_name: NLLSurvLoss
  alpha_surv: 0.4
Data:
  dataset_name: Clam_data
  parent_dir: /home/data/tcga_prad/
  wsifeat_dir: histo_model_preproc/1024_40/UNI/_2_features/pt_files
  clin_file: tabular_data/clindata/tcga_prad_clin_imputed.csv
  omics_file: tabular_data/genomicdata/rnaseq_in_pways_tpm.csv
  label_dir: tabular_data/cross_val_tables/seed99999/batchstrat
  log_path: logs/CLAM_batchstrat_dseed99999_patchsize1024_encoderUNI_allclinical_alpha0.4_lr0.0001
  max_slides: 1
  train_dataloader:
    batch_size: 1
    num_workers: 1
  test_dataloader:
    batch_size: 1
    num_workers: 1
ModelInfo:
  name: CLAM
  params:
    wsi_hidden_sizes: null
    concat_hidden_sizes:
    - 16
    - 8
    n_classes: 4
    dropout: false
    clin_vars:
    - has_PSM
    - has_SVI
    - has_ECE
    - has_LNI
    - gleason_grade
    - diagnosis_age
  n_classes: 4
Optimizer:
  opt: adam
  lr: 0.0001
  weight_decay: 1.0e-05
