General:
  comment: HVTSurv
  seed: 2021
  grad_acc: 16
  epochs: 20
  frozen_bn: false
  patience: 20
  server: train
Loss:
  loss_name: NLLSurvLoss
  alpha_surv: 0.4
Data:
  dataset_name: hvt_data
  parent_dir: /home/data/tcga_prad/
  wsifeat_dir: histo_model_preproc/1024_40/UNI/_4_mask_window/seed99999/_3_knn_2_0.5_random
  clin_file: tabular_data/clindata/tcga_prad_clin_imputed.csv
  label_dir: histo_model_preproc/1024_40/UNI/_4_mask_window/seed99999/batchstrat_2
  omics_file: tabular_data/genomicdata/rnaseq_in_pways_tpm.csv
  log_path: logs/hvtsurv_batchstrat_dseed99999_patchsize1024_encoderUNI_noclin_alpha0.4_lr0.0002
  max_slides: 1
  train_dataloader:
    batch_size: 1
    num_workers: 1
  test_dataloader:
    batch_size: 1
    num_workers: 1
ModelInfo:
  name: HVTSurv
  params:
    window_size: 49
    wsi_hidden_sizes: null
    concat_hidden_sizes:
    - 16
    - 8
    n_classes: 4
    dropout: true
    clin_vars: []
  n_classes: 4
Optimizer:
  opt: adam
  lr: 0.0002
  weight_decay: 1.0e-05
